namespace ColorPicker.UITests.Tests;

/// <summary>
/// Empirically captured picker dark-spot positions for each (cell, color) pair,
/// expressed as (relX, relY) inside the cell's wheel-area bounds (0..1).
///
/// Generated by <see cref="ColorSyncDataGenerator"/>. To regenerate after a
/// rendering change, run:
///   $env:GEN_PICKER_DATA = "1"
///   dotnet test --filter Generate_ExpectedPickerOffsets
/// then paste the generator output into <see cref="Offsets"/> below.
///
/// Tests use this table as the single source of truth for "where should the
/// picker indicator be on screen?" — no hue/sat/angle math at test time.
/// </summary>
internal static class ColorSyncExpectedPickerOffsets
{
    public static readonly IReadOnlyDictionary<(string Cell, string Hex), (double Rx, double Ry)> Offsets =
        new Dictionary<(string, string), (double, double)>
    {
        [("C_WheelDefault", "#FF0000FF")] = (0.2500, 0.5550), // red           luma=0
        [("C_TriRotate",    "#FF0000FF")] = (0.1189, 0.5211), // red           luma=0
        [("C_WheelDefault", "#00FF00FF")] = (0.6311, 0.7906), // green         luma=2
        [("C_TriRotate",    "#00FF00FF")] = (0.6639, 0.8947), // green         luma=0
        [("C_WheelDefault", "#0000FFFF")] = (0.5902, 0.2513), // blue          luma=1
        [("C_TriRotate",    "#0000FFFF")] = (0.6803, 0.1105), // blue          luma=0
        [("C_WheelDefault", "#FFFF00FF")] = (0.3648, 0.7906), // yellow        luma=3
        [("C_TriRotate",    "#FFFF00FF")] = (0.3320, 0.8947), // yellow        luma=0
        [("C_WheelDefault", "#00FFFFFF")] = (0.7459, 0.5550), // cyan          luma=3
        [("C_TriRotate",    "#00FFFFFF")] = (0.8279, 0.5211), // cyan          luma=0
        [("C_WheelDefault", "#FF00FFFF")] = (0.3320, 0.2356), // magenta       luma=0
        [("C_TriRotate",    "#FF00FFFF")] = (0.3074, 0.1105), // magenta       luma=0
        [("C_WheelDefault", "#FFA500FF")] = (0.2910, 0.6911), // orange        luma=0
        [("C_TriRotate",    "#FFA500FF")] = (0.2213, 0.8053), // orange        luma=0
        [("C_WheelDefault", "#FF000080")] = (0.2500, 0.5550), // red-alpha-50  luma=0
        [("C_TriRotate",    "#FF000080")] = (0.1189, 0.5211), // red-alpha-50  luma=0
    };
}
